kind: pipeline
type: docker
name: 编译
steps:
- name: build
  image: rust:1.64.0-alpine3.16
  commands:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk add git musl-dev linux-headers libressl-dev
    - rustup target add x86_64-unknown-linux-musl
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .
    - git clone https://github.com/gngpp/aliyundrive-cli.git
    - cd ./aliyundrive-cli && cargo run encode_string --target x86_64-lin-linux-musl
steps:
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: aliyundrive-cli/*
    target: /autobuild/
