kind: pipeline
type: docker
name: build

steps:
- name: 编译
  image: rust:alpine3.16
  commands:
  - apk update
  - apk add git bash
  - git clone https://github.com/20020314/aliyundrive-cli.git
  - cd aliyundrive-cli
  - cargo run encode_string --target x86_64-lin-linux-musl
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: aliyundrive-cli/x86_64-lin*
    target: /autobuild/
