kind: pipeline
type: docker
name: build

steps:
- name: 编译
  image: rust:1.64.0-bullseye
  commands:
  - git clone https://github.com/20020314/aliyundrive-cli.git
  - cd aliyundrive-cli
  - cargo build --color=always --release
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: aliyundrive-cli/*
    target: /autobuild/
