kind: pipeline
type: docker
name: build
clone:
  disable: true
steps:
- name: 编译
  image: rust:alpine3.16
  commands:
  - apk update
  - apk add git musl-dev linux-headers libressl-dev git bash
  - rustup target add x86_64-unknown-linux-musl
  - git clone https://github.com/20020314/aliyundrive-cli.git
  - cd aliyundrive-cli
  - cargo run encode_string --target x86_64-unknown-linux-musl
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: aliyundrive-cli/**/*
    target: /autobuild/
